/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AtualizarCadastroRouteImport } from './routes/atualizar-cadastro'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DocumentacaoRouteRouteImport } from './routes/documentacao/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedShellRouteRouteImport } from './routes/_authenticated/_shell/route'
import { Route as AuthenticatedSelecionarCapituloRouteImport } from './routes/_authenticated/selecionar-capitulo'
import { Route as AtaTokenRouteImport } from './routes/ata.$token'
import { Route as CTokenRouteImport } from './routes/c.$token'
import { Route as DocumentacaoIndexRouteImport } from './routes/documentacao/index'
import { Route as DocumentacaoGuiaRouteImport } from './routes/documentacao/guia'
import { Route as DocumentacaoOpenSourceRouteImport } from './routes/documentacao/open-source'
import { Route as DocumentacaoTecnicaRouteImport } from './routes/documentacao/tecnica'
import { Route as FluxoCaixaTokenRouteImport } from './routes/fluxo-caixa.$token'
import { Route as MensalidadesTokenRouteImport } from './routes/mensalidades.$token'
import { Route as AuthenticatedShellAtasRouteImport } from './routes/_authenticated/_shell/atas'
import { Route as AuthenticatedShellCalendarioRouteImport } from './routes/_authenticated/_shell/calendario'
import { Route as AuthenticatedShellConfiguracoesRouteImport } from './routes/_authenticated/_shell/configuracoes'
import { Route as AuthenticatedShellFinanceiroRouteImport } from './routes/_authenticated/_shell/financeiro'
import { Route as AuthenticatedShellGestaoRouteImport } from './routes/_authenticated/_shell/gestao'
import { Route as AuthenticatedShellInicioRouteImport } from './routes/_authenticated/_shell/inicio'
import { Route as AuthenticatedShellMaisRouteImport } from './routes/_authenticated/_shell/mais'
import { Route as AuthenticatedShellPerfilRouteImport } from './routes/_authenticated/_shell/perfil'
import { Route as AuthenticatedShellPresencasRouteImport } from './routes/_authenticated/_shell/presencas'
import { Route as CTokenIndexRouteImport } from './routes/c.$token.index'
import { Route as CTokenEuRouteImport } from './routes/c.$token.eu'
import { Route as CTokenFluxoRouteImport } from './routes/c.$token.fluxo'
import { Route as CTokenMensalidadesRouteImport } from './routes/c.$token.mensalidades'
import { Route as CTokenPresencasRouteImport } from './routes/c.$token.presencas'
import { Route as AuthenticatedShellEventosIndexRouteImport } from './routes/_authenticated/_shell/eventos.index'
import { Route as AuthenticatedShellEventosIdRouteImport } from './routes/_authenticated/_shell/eventos.$id'
import { Route as AuthenticatedShellEventosCheckinsRouteImport } from './routes/_authenticated/_shell/eventos.checkins'
import { Route as AuthenticatedShellEventosNovoRouteImport } from './routes/_authenticated/_shell/eventos.novo'
import { Route as AuthenticatedShellHospitalariaCardapiosRouteImport } from './routes/_authenticated/_shell/hospitalaria.cardapios'
import { Route as AuthenticatedShellHospitalariaEscalaRouteImport } from './routes/_authenticated/_shell/hospitalaria.escala'
import { Route as AuthenticatedShellMembrosIndexRouteImport } from './routes/_authenticated/_shell/membros.index'
import { Route as AuthenticatedShellMembrosIdRouteImport } from './routes/_authenticated/_shell/membros.$id'
import { Route as AuthenticatedShellMembrosNovoRouteImport } from './routes/_authenticated/_shell/membros.novo'
import { Route as AuthenticatedShellOngoingIdRouteImport } from './routes/_authenticated/_shell/ongoing.$id'
import { Route as AuthenticatedShellRegionalIndexRouteImport } from './routes/_authenticated/_shell/regional.index'
import { Route as AuthenticatedShellRegionalCalendarioRouteImport } from './routes/_authenticated/_shell/regional.calendario'
import { Route as AuthenticatedShellRegionalCapitulosRouteImport } from './routes/_authenticated/_shell/regional.capitulos'
import { Route as AuthenticatedShellRegionalMembrosRouteImport } from './routes/_authenticated/_shell/regional.membros'
import { Route as AuthenticatedShellRegionalRegioesRouteImport } from './routes/_authenticated/_shell/regional.regioes'
import { Route as AuthenticatedShellSindicanciasFichasRouteImport } from './routes/_authenticated/_shell/sindicancias.fichas'
import { Route as AuthenticatedShellSindicanciasProcessosRouteImport } from './routes/_authenticated/_shell/sindicancias.processos'
import { Route as AuthenticatedShellTesourariaCobrancasRouteImport } from './routes/_authenticated/_shell/tesouraria.cobrancas'
import { Route as AuthenticatedShellTesourariaFluxoRouteImport } from './routes/_authenticated/_shell/tesouraria.fluxo'
import { Route as AuthenticatedShellTesourariaMensalidadesRouteImport } from './routes/_authenticated/_shell/tesouraria.mensalidades'
import { Route as AuthenticatedShellMembrosIdEditarRouteImport } from './routes/_authenticated/_shell/membros.$id_.editar'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AtualizarCadastroRoute = AtualizarCadastroRouteImport.update({
  id: '/atualizar-cadastro',
  path: '/atualizar-cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentacaoRouteRoute = DocumentacaoRouteRouteImport.update({
  id: '/documentacao',
  path: '/documentacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShellRouteRoute = AuthenticatedShellRouteRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSelecionarCapituloRoute =
  AuthenticatedSelecionarCapituloRouteImport.update({
    id: '/selecionar-capitulo',
    path: '/selecionar-capitulo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AtaTokenRoute = AtaTokenRouteImport.update({
  id: '/ata/$token',
  path: '/ata/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CTokenRoute = CTokenRouteImport.update({
  id: '/c/$token',
  path: '/c/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentacaoIndexRoute = DocumentacaoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentacaoRouteRoute,
} as any)
const DocumentacaoGuiaRoute = DocumentacaoGuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => DocumentacaoRouteRoute,
} as any)
const DocumentacaoOpenSourceRoute = DocumentacaoOpenSourceRouteImport.update({
  id: '/open-source',
  path: '/open-source',
  getParentRoute: () => DocumentacaoRouteRoute,
} as any)
const DocumentacaoTecnicaRoute = DocumentacaoTecnicaRouteImport.update({
  id: '/tecnica',
  path: '/tecnica',
  getParentRoute: () => DocumentacaoRouteRoute,
} as any)
const FluxoCaixaTokenRoute = FluxoCaixaTokenRouteImport.update({
  id: '/fluxo-caixa/$token',
  path: '/fluxo-caixa/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MensalidadesTokenRoute = MensalidadesTokenRouteImport.update({
  id: '/mensalidades/$token',
  path: '/mensalidades/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShellAtasRoute = AuthenticatedShellAtasRouteImport.update({
  id: '/atas',
  path: '/atas',
  getParentRoute: () => AuthenticatedShellRouteRoute,
} as any)
const AuthenticatedShellCalendarioRoute =
  AuthenticatedShellCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellConfiguracoesRoute =
  AuthenticatedShellConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellFinanceiroRoute =
  AuthenticatedShellFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellGestaoRoute =
  AuthenticatedShellGestaoRouteImport.update({
    id: '/gestao',
    path: '/gestao',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellInicioRoute =
  AuthenticatedShellInicioRouteImport.update({
    id: '/inicio',
    path: '/inicio',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellMaisRoute = AuthenticatedShellMaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => AuthenticatedShellRouteRoute,
} as any)
const AuthenticatedShellPerfilRoute =
  AuthenticatedShellPerfilRouteImport.update({
    id: '/perfil',
    path: '/perfil',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellPresencasRoute =
  AuthenticatedShellPresencasRouteImport.update({
    id: '/presencas',
    path: '/presencas',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const CTokenIndexRoute = CTokenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CTokenRoute,
} as any)
const CTokenEuRoute = CTokenEuRouteImport.update({
  id: '/eu',
  path: '/eu',
  getParentRoute: () => CTokenRoute,
} as any)
const CTokenFluxoRoute = CTokenFluxoRouteImport.update({
  id: '/fluxo',
  path: '/fluxo',
  getParentRoute: () => CTokenRoute,
} as any)
const CTokenMensalidadesRoute = CTokenMensalidadesRouteImport.update({
  id: '/mensalidades',
  path: '/mensalidades',
  getParentRoute: () => CTokenRoute,
} as any)
const CTokenPresencasRoute = CTokenPresencasRouteImport.update({
  id: '/presencas',
  path: '/presencas',
  getParentRoute: () => CTokenRoute,
} as any)
const AuthenticatedShellEventosIndexRoute =
  AuthenticatedShellEventosIndexRouteImport.update({
    id: '/eventos/',
    path: '/eventos/',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellEventosIdRoute =
  AuthenticatedShellEventosIdRouteImport.update({
    id: '/eventos/$id',
    path: '/eventos/$id',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellEventosCheckinsRoute =
  AuthenticatedShellEventosCheckinsRouteImport.update({
    id: '/eventos/checkins',
    path: '/eventos/checkins',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellEventosNovoRoute =
  AuthenticatedShellEventosNovoRouteImport.update({
    id: '/eventos/novo',
    path: '/eventos/novo',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellHospitalariaCardapiosRoute =
  AuthenticatedShellHospitalariaCardapiosRouteImport.update({
    id: '/hospitalaria/cardapios',
    path: '/hospitalaria/cardapios',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellHospitalariaEscalaRoute =
  AuthenticatedShellHospitalariaEscalaRouteImport.update({
    id: '/hospitalaria/escala',
    path: '/hospitalaria/escala',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellMembrosIndexRoute =
  AuthenticatedShellMembrosIndexRouteImport.update({
    id: '/membros/',
    path: '/membros/',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellMembrosIdRoute =
  AuthenticatedShellMembrosIdRouteImport.update({
    id: '/membros/$id',
    path: '/membros/$id',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellMembrosNovoRoute =
  AuthenticatedShellMembrosNovoRouteImport.update({
    id: '/membros/novo',
    path: '/membros/novo',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellOngoingIdRoute =
  AuthenticatedShellOngoingIdRouteImport.update({
    id: '/ongoing/$id',
    path: '/ongoing/$id',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellRegionalIndexRoute =
  AuthenticatedShellRegionalIndexRouteImport.update({
    id: '/regional/',
    path: '/regional/',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellRegionalCalendarioRoute =
  AuthenticatedShellRegionalCalendarioRouteImport.update({
    id: '/regional/calendario',
    path: '/regional/calendario',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellRegionalCapitulosRoute =
  AuthenticatedShellRegionalCapitulosRouteImport.update({
    id: '/regional/capitulos',
    path: '/regional/capitulos',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellRegionalMembrosRoute =
  AuthenticatedShellRegionalMembrosRouteImport.update({
    id: '/regional/membros',
    path: '/regional/membros',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellRegionalRegioesRoute =
  AuthenticatedShellRegionalRegioesRouteImport.update({
    id: '/regional/regioes',
    path: '/regional/regioes',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellSindicanciasFichasRoute =
  AuthenticatedShellSindicanciasFichasRouteImport.update({
    id: '/sindicancias/fichas',
    path: '/sindicancias/fichas',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellSindicanciasProcessosRoute =
  AuthenticatedShellSindicanciasProcessosRouteImport.update({
    id: '/sindicancias/processos',
    path: '/sindicancias/processos',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellTesourariaCobrancasRoute =
  AuthenticatedShellTesourariaCobrancasRouteImport.update({
    id: '/tesouraria/cobrancas',
    path: '/tesouraria/cobrancas',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellTesourariaFluxoRoute =
  AuthenticatedShellTesourariaFluxoRouteImport.update({
    id: '/tesouraria/fluxo',
    path: '/tesouraria/fluxo',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellTesourariaMensalidadesRoute =
  AuthenticatedShellTesourariaMensalidadesRouteImport.update({
    id: '/tesouraria/mensalidades',
    path: '/tesouraria/mensalidades',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)
const AuthenticatedShellMembrosIdEditarRoute =
  AuthenticatedShellMembrosIdEditarRouteImport.update({
    id: '/membros/$id_/editar',
    path: '/membros/$id/editar',
    getParentRoute: () => AuthenticatedShellRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/documentacao': typeof DocumentacaoRouteRouteWithChildren
  '/atualizar-cadastro': typeof AtualizarCadastroRoute
  '/auth': typeof AuthRoute
  '/selecionar-capitulo': typeof AuthenticatedSelecionarCapituloRoute
  '/ata/$token': typeof AtaTokenRoute
  '/c/$token': typeof CTokenRouteWithChildren
  '/documentacao/guia': typeof DocumentacaoGuiaRoute
  '/documentacao/open-source': typeof DocumentacaoOpenSourceRoute
  '/documentacao/tecnica': typeof DocumentacaoTecnicaRoute
  '/fluxo-caixa/$token': typeof FluxoCaixaTokenRoute
  '/mensalidades/$token': typeof MensalidadesTokenRoute
  '/documentacao/': typeof DocumentacaoIndexRoute
  '/atas': typeof AuthenticatedShellAtasRoute
  '/calendario': typeof AuthenticatedShellCalendarioRoute
  '/configuracoes': typeof AuthenticatedShellConfiguracoesRoute
  '/financeiro': typeof AuthenticatedShellFinanceiroRoute
  '/gestao': typeof AuthenticatedShellGestaoRoute
  '/inicio': typeof AuthenticatedShellInicioRoute
  '/mais': typeof AuthenticatedShellMaisRoute
  '/perfil': typeof AuthenticatedShellPerfilRoute
  '/presencas': typeof AuthenticatedShellPresencasRoute
  '/c/$token/eu': typeof CTokenEuRoute
  '/c/$token/fluxo': typeof CTokenFluxoRoute
  '/c/$token/mensalidades': typeof CTokenMensalidadesRoute
  '/c/$token/presencas': typeof CTokenPresencasRoute
  '/c/$token/': typeof CTokenIndexRoute
  '/eventos/$id': typeof AuthenticatedShellEventosIdRoute
  '/eventos/checkins': typeof AuthenticatedShellEventosCheckinsRoute
  '/eventos/novo': typeof AuthenticatedShellEventosNovoRoute
  '/hospitalaria/cardapios': typeof AuthenticatedShellHospitalariaCardapiosRoute
  '/hospitalaria/escala': typeof AuthenticatedShellHospitalariaEscalaRoute
  '/membros/$id': typeof AuthenticatedShellMembrosIdRoute
  '/membros/novo': typeof AuthenticatedShellMembrosNovoRoute
  '/ongoing/$id': typeof AuthenticatedShellOngoingIdRoute
  '/regional/calendario': typeof AuthenticatedShellRegionalCalendarioRoute
  '/regional/capitulos': typeof AuthenticatedShellRegionalCapitulosRoute
  '/regional/membros': typeof AuthenticatedShellRegionalMembrosRoute
  '/regional/regioes': typeof AuthenticatedShellRegionalRegioesRoute
  '/sindicancias/fichas': typeof AuthenticatedShellSindicanciasFichasRoute
  '/sindicancias/processos': typeof AuthenticatedShellSindicanciasProcessosRoute
  '/tesouraria/cobrancas': typeof AuthenticatedShellTesourariaCobrancasRoute
  '/tesouraria/fluxo': typeof AuthenticatedShellTesourariaFluxoRoute
  '/tesouraria/mensalidades': typeof AuthenticatedShellTesourariaMensalidadesRoute
  '/eventos/': typeof AuthenticatedShellEventosIndexRoute
  '/membros/': typeof AuthenticatedShellMembrosIndexRoute
  '/regional/': typeof AuthenticatedShellRegionalIndexRoute
  '/membros/$id/editar': typeof AuthenticatedShellMembrosIdEditarRoute
}
export interface FileRoutesByTo {
  '/atualizar-cadastro': typeof AtualizarCadastroRoute
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/selecionar-capitulo': typeof AuthenticatedSelecionarCapituloRoute
  '/ata/$token': typeof AtaTokenRoute
  '/documentacao/guia': typeof DocumentacaoGuiaRoute
  '/documentacao/open-source': typeof DocumentacaoOpenSourceRoute
  '/documentacao/tecnica': typeof DocumentacaoTecnicaRoute
  '/fluxo-caixa/$token': typeof FluxoCaixaTokenRoute
  '/mensalidades/$token': typeof MensalidadesTokenRoute
  '/documentacao': typeof DocumentacaoIndexRoute
  '/atas': typeof AuthenticatedShellAtasRoute
  '/calendario': typeof AuthenticatedShellCalendarioRoute
  '/configuracoes': typeof AuthenticatedShellConfiguracoesRoute
  '/financeiro': typeof AuthenticatedShellFinanceiroRoute
  '/gestao': typeof AuthenticatedShellGestaoRoute
  '/inicio': typeof AuthenticatedShellInicioRoute
  '/mais': typeof AuthenticatedShellMaisRoute
  '/perfil': typeof AuthenticatedShellPerfilRoute
  '/presencas': typeof AuthenticatedShellPresencasRoute
  '/c/$token/eu': typeof CTokenEuRoute
  '/c/$token/fluxo': typeof CTokenFluxoRoute
  '/c/$token/mensalidades': typeof CTokenMensalidadesRoute
  '/c/$token/presencas': typeof CTokenPresencasRoute
  '/c/$token': typeof CTokenIndexRoute
  '/eventos/$id': typeof AuthenticatedShellEventosIdRoute
  '/eventos/checkins': typeof AuthenticatedShellEventosCheckinsRoute
  '/eventos/novo': typeof AuthenticatedShellEventosNovoRoute
  '/hospitalaria/cardapios': typeof AuthenticatedShellHospitalariaCardapiosRoute
  '/hospitalaria/escala': typeof AuthenticatedShellHospitalariaEscalaRoute
  '/membros/$id': typeof AuthenticatedShellMembrosIdRoute
  '/membros/novo': typeof AuthenticatedShellMembrosNovoRoute
  '/ongoing/$id': typeof AuthenticatedShellOngoingIdRoute
  '/regional/calendario': typeof AuthenticatedShellRegionalCalendarioRoute
  '/regional/capitulos': typeof AuthenticatedShellRegionalCapitulosRoute
  '/regional/membros': typeof AuthenticatedShellRegionalMembrosRoute
  '/regional/regioes': typeof AuthenticatedShellRegionalRegioesRoute
  '/sindicancias/fichas': typeof AuthenticatedShellSindicanciasFichasRoute
  '/sindicancias/processos': typeof AuthenticatedShellSindicanciasProcessosRoute
  '/tesouraria/cobrancas': typeof AuthenticatedShellTesourariaCobrancasRoute
  '/tesouraria/fluxo': typeof AuthenticatedShellTesourariaFluxoRoute
  '/tesouraria/mensalidades': typeof AuthenticatedShellTesourariaMensalidadesRoute
  '/eventos': typeof AuthenticatedShellEventosIndexRoute
  '/membros': typeof AuthenticatedShellMembrosIndexRoute
  '/regional': typeof AuthenticatedShellRegionalIndexRoute
  '/membros/$id/editar': typeof AuthenticatedShellMembrosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/documentacao': typeof DocumentacaoRouteRouteWithChildren
  '/atualizar-cadastro': typeof AtualizarCadastroRoute
  '/auth': typeof AuthRoute
  '/_authenticated/_shell': typeof AuthenticatedShellRouteRouteWithChildren
  '/_authenticated/selecionar-capitulo': typeof AuthenticatedSelecionarCapituloRoute
  '/ata/$token': typeof AtaTokenRoute
  '/c/$token': typeof CTokenRouteWithChildren
  '/documentacao/guia': typeof DocumentacaoGuiaRoute
  '/documentacao/open-source': typeof DocumentacaoOpenSourceRoute
  '/documentacao/tecnica': typeof DocumentacaoTecnicaRoute
  '/fluxo-caixa/$token': typeof FluxoCaixaTokenRoute
  '/mensalidades/$token': typeof MensalidadesTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/documentacao/': typeof DocumentacaoIndexRoute
  '/_authenticated/_shell/atas': typeof AuthenticatedShellAtasRoute
  '/_authenticated/_shell/calendario': typeof AuthenticatedShellCalendarioRoute
  '/_authenticated/_shell/configuracoes': typeof AuthenticatedShellConfiguracoesRoute
  '/_authenticated/_shell/financeiro': typeof AuthenticatedShellFinanceiroRoute
  '/_authenticated/_shell/gestao': typeof AuthenticatedShellGestaoRoute
  '/_authenticated/_shell/inicio': typeof AuthenticatedShellInicioRoute
  '/_authenticated/_shell/mais': typeof AuthenticatedShellMaisRoute
  '/_authenticated/_shell/perfil': typeof AuthenticatedShellPerfilRoute
  '/_authenticated/_shell/presencas': typeof AuthenticatedShellPresencasRoute
  '/c/$token/eu': typeof CTokenEuRoute
  '/c/$token/fluxo': typeof CTokenFluxoRoute
  '/c/$token/mensalidades': typeof CTokenMensalidadesRoute
  '/c/$token/presencas': typeof CTokenPresencasRoute
  '/c/$token/': typeof CTokenIndexRoute
  '/_authenticated/_shell/eventos/$id': typeof AuthenticatedShellEventosIdRoute
  '/_authenticated/_shell/eventos/checkins': typeof AuthenticatedShellEventosCheckinsRoute
  '/_authenticated/_shell/eventos/novo': typeof AuthenticatedShellEventosNovoRoute
  '/_authenticated/_shell/hospitalaria/cardapios': typeof AuthenticatedShellHospitalariaCardapiosRoute
  '/_authenticated/_shell/hospitalaria/escala': typeof AuthenticatedShellHospitalariaEscalaRoute
  '/_authenticated/_shell/membros/$id': typeof AuthenticatedShellMembrosIdRoute
  '/_authenticated/_shell/membros/novo': typeof AuthenticatedShellMembrosNovoRoute
  '/_authenticated/_shell/ongoing/$id': typeof AuthenticatedShellOngoingIdRoute
  '/_authenticated/_shell/regional/calendario': typeof AuthenticatedShellRegionalCalendarioRoute
  '/_authenticated/_shell/regional/capitulos': typeof AuthenticatedShellRegionalCapitulosRoute
  '/_authenticated/_shell/regional/membros': typeof AuthenticatedShellRegionalMembrosRoute
  '/_authenticated/_shell/regional/regioes': typeof AuthenticatedShellRegionalRegioesRoute
  '/_authenticated/_shell/sindicancias/fichas': typeof AuthenticatedShellSindicanciasFichasRoute
  '/_authenticated/_shell/sindicancias/processos': typeof AuthenticatedShellSindicanciasProcessosRoute
  '/_authenticated/_shell/tesouraria/cobrancas': typeof AuthenticatedShellTesourariaCobrancasRoute
  '/_authenticated/_shell/tesouraria/fluxo': typeof AuthenticatedShellTesourariaFluxoRoute
  '/_authenticated/_shell/tesouraria/mensalidades': typeof AuthenticatedShellTesourariaMensalidadesRoute
  '/_authenticated/_shell/eventos/': typeof AuthenticatedShellEventosIndexRoute
  '/_authenticated/_shell/membros/': typeof AuthenticatedShellMembrosIndexRoute
  '/_authenticated/_shell/regional/': typeof AuthenticatedShellRegionalIndexRoute
  '/_authenticated/_shell/membros/$id_/editar': typeof AuthenticatedShellMembrosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documentacao'
    | '/atualizar-cadastro'
    | '/auth'
    | '/selecionar-capitulo'
    | '/ata/$token'
    | '/c/$token'
    | '/documentacao/guia'
    | '/documentacao/open-source'
    | '/documentacao/tecnica'
    | '/fluxo-caixa/$token'
    | '/mensalidades/$token'
    | '/documentacao/'
    | '/atas'
    | '/calendario'
    | '/configuracoes'
    | '/financeiro'
    | '/gestao'
    | '/inicio'
    | '/mais'
    | '/perfil'
    | '/presencas'
    | '/c/$token/eu'
    | '/c/$token/fluxo'
    | '/c/$token/mensalidades'
    | '/c/$token/presencas'
    | '/c/$token/'
    | '/eventos/$id'
    | '/eventos/checkins'
    | '/eventos/novo'
    | '/hospitalaria/cardapios'
    | '/hospitalaria/escala'
    | '/membros/$id'
    | '/membros/novo'
    | '/ongoing/$id'
    | '/regional/calendario'
    | '/regional/capitulos'
    | '/regional/membros'
    | '/regional/regioes'
    | '/sindicancias/fichas'
    | '/sindicancias/processos'
    | '/tesouraria/cobrancas'
    | '/tesouraria/fluxo'
    | '/tesouraria/mensalidades'
    | '/eventos/'
    | '/membros/'
    | '/regional/'
    | '/membros/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/atualizar-cadastro'
    | '/auth'
    | '/'
    | '/selecionar-capitulo'
    | '/ata/$token'
    | '/documentacao/guia'
    | '/documentacao/open-source'
    | '/documentacao/tecnica'
    | '/fluxo-caixa/$token'
    | '/mensalidades/$token'
    | '/documentacao'
    | '/atas'
    | '/calendario'
    | '/configuracoes'
    | '/financeiro'
    | '/gestao'
    | '/inicio'
    | '/mais'
    | '/perfil'
    | '/presencas'
    | '/c/$token/eu'
    | '/c/$token/fluxo'
    | '/c/$token/mensalidades'
    | '/c/$token/presencas'
    | '/c/$token'
    | '/eventos/$id'
    | '/eventos/checkins'
    | '/eventos/novo'
    | '/hospitalaria/cardapios'
    | '/hospitalaria/escala'
    | '/membros/$id'
    | '/membros/novo'
    | '/ongoing/$id'
    | '/regional/calendario'
    | '/regional/capitulos'
    | '/regional/membros'
    | '/regional/regioes'
    | '/sindicancias/fichas'
    | '/sindicancias/processos'
    | '/tesouraria/cobrancas'
    | '/tesouraria/fluxo'
    | '/tesouraria/mensalidades'
    | '/eventos'
    | '/membros'
    | '/regional'
    | '/membros/$id/editar'
  id:
    | '__root__'
    | '/_authenticated'
    | '/documentacao'
    | '/atualizar-cadastro'
    | '/auth'
    | '/_authenticated/_shell'
    | '/_authenticated/selecionar-capitulo'
    | '/ata/$token'
    | '/c/$token'
    | '/documentacao/guia'
    | '/documentacao/open-source'
    | '/documentacao/tecnica'
    | '/fluxo-caixa/$token'
    | '/mensalidades/$token'
    | '/_authenticated/'
    | '/documentacao/'
    | '/_authenticated/_shell/atas'
    | '/_authenticated/_shell/calendario'
    | '/_authenticated/_shell/configuracoes'
    | '/_authenticated/_shell/financeiro'
    | '/_authenticated/_shell/gestao'
    | '/_authenticated/_shell/inicio'
    | '/_authenticated/_shell/mais'
    | '/_authenticated/_shell/perfil'
    | '/_authenticated/_shell/presencas'
    | '/c/$token/eu'
    | '/c/$token/fluxo'
    | '/c/$token/mensalidades'
    | '/c/$token/presencas'
    | '/c/$token/'
    | '/_authenticated/_shell/eventos/$id'
    | '/_authenticated/_shell/eventos/checkins'
    | '/_authenticated/_shell/eventos/novo'
    | '/_authenticated/_shell/hospitalaria/cardapios'
    | '/_authenticated/_shell/hospitalaria/escala'
    | '/_authenticated/_shell/membros/$id'
    | '/_authenticated/_shell/membros/novo'
    | '/_authenticated/_shell/ongoing/$id'
    | '/_authenticated/_shell/regional/calendario'
    | '/_authenticated/_shell/regional/capitulos'
    | '/_authenticated/_shell/regional/membros'
    | '/_authenticated/_shell/regional/regioes'
    | '/_authenticated/_shell/sindicancias/fichas'
    | '/_authenticated/_shell/sindicancias/processos'
    | '/_authenticated/_shell/tesouraria/cobrancas'
    | '/_authenticated/_shell/tesouraria/fluxo'
    | '/_authenticated/_shell/tesouraria/mensalidades'
    | '/_authenticated/_shell/eventos/'
    | '/_authenticated/_shell/membros/'
    | '/_authenticated/_shell/regional/'
    | '/_authenticated/_shell/membros/$id_/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  DocumentacaoRouteRoute: typeof DocumentacaoRouteRouteWithChildren
  AtualizarCadastroRoute: typeof AtualizarCadastroRoute
  AuthRoute: typeof AuthRoute
  AtaTokenRoute: typeof AtaTokenRoute
  CTokenRoute: typeof CTokenRouteWithChildren
  FluxoCaixaTokenRoute: typeof FluxoCaixaTokenRoute
  MensalidadesTokenRoute: typeof MensalidadesTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atualizar-cadastro': {
      id: '/atualizar-cadastro'
      path: '/atualizar-cadastro'
      fullPath: '/atualizar-cadastro'
      preLoaderRoute: typeof AtualizarCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentacao': {
      id: '/documentacao'
      path: '/documentacao'
      fullPath: '/documentacao'
      preLoaderRoute: typeof DocumentacaoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_shell': {
      id: '/_authenticated/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedShellRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/selecionar-capitulo': {
      id: '/_authenticated/selecionar-capitulo'
      path: '/selecionar-capitulo'
      fullPath: '/selecionar-capitulo'
      preLoaderRoute: typeof AuthenticatedSelecionarCapituloRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/ata/$token': {
      id: '/ata/$token'
      path: '/ata/$token'
      fullPath: '/ata/$token'
      preLoaderRoute: typeof AtaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$token': {
      id: '/c/$token'
      path: '/c/$token'
      fullPath: '/c/$token'
      preLoaderRoute: typeof CTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentacao/': {
      id: '/documentacao/'
      path: '/'
      fullPath: '/documentacao/'
      preLoaderRoute: typeof DocumentacaoIndexRouteImport
      parentRoute: typeof DocumentacaoRouteRoute
    }
    '/documentacao/guia': {
      id: '/documentacao/guia'
      path: '/guia'
      fullPath: '/documentacao/guia'
      preLoaderRoute: typeof DocumentacaoGuiaRouteImport
      parentRoute: typeof DocumentacaoRouteRoute
    }
    '/documentacao/open-source': {
      id: '/documentacao/open-source'
      path: '/open-source'
      fullPath: '/documentacao/open-source'
      preLoaderRoute: typeof DocumentacaoOpenSourceRouteImport
      parentRoute: typeof DocumentacaoRouteRoute
    }
    '/documentacao/tecnica': {
      id: '/documentacao/tecnica'
      path: '/tecnica'
      fullPath: '/documentacao/tecnica'
      preLoaderRoute: typeof DocumentacaoTecnicaRouteImport
      parentRoute: typeof DocumentacaoRouteRoute
    }
    '/fluxo-caixa/$token': {
      id: '/fluxo-caixa/$token'
      path: '/fluxo-caixa/$token'
      fullPath: '/fluxo-caixa/$token'
      preLoaderRoute: typeof FluxoCaixaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensalidades/$token': {
      id: '/mensalidades/$token'
      path: '/mensalidades/$token'
      fullPath: '/mensalidades/$token'
      preLoaderRoute: typeof MensalidadesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_shell/atas': {
      id: '/_authenticated/_shell/atas'
      path: '/atas'
      fullPath: '/atas'
      preLoaderRoute: typeof AuthenticatedShellAtasRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/calendario': {
      id: '/_authenticated/_shell/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof AuthenticatedShellCalendarioRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/configuracoes': {
      id: '/_authenticated/_shell/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedShellConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/financeiro': {
      id: '/_authenticated/_shell/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedShellFinanceiroRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/gestao': {
      id: '/_authenticated/_shell/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof AuthenticatedShellGestaoRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/inicio': {
      id: '/_authenticated/_shell/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedShellInicioRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/mais': {
      id: '/_authenticated/_shell/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof AuthenticatedShellMaisRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/perfil': {
      id: '/_authenticated/_shell/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedShellPerfilRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/presencas': {
      id: '/_authenticated/_shell/presencas'
      path: '/presencas'
      fullPath: '/presencas'
      preLoaderRoute: typeof AuthenticatedShellPresencasRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/c/$token/': {
      id: '/c/$token/'
      path: '/'
      fullPath: '/c/$token/'
      preLoaderRoute: typeof CTokenIndexRouteImport
      parentRoute: typeof CTokenRoute
    }
    '/c/$token/eu': {
      id: '/c/$token/eu'
      path: '/eu'
      fullPath: '/c/$token/eu'
      preLoaderRoute: typeof CTokenEuRouteImport
      parentRoute: typeof CTokenRoute
    }
    '/c/$token/fluxo': {
      id: '/c/$token/fluxo'
      path: '/fluxo'
      fullPath: '/c/$token/fluxo'
      preLoaderRoute: typeof CTokenFluxoRouteImport
      parentRoute: typeof CTokenRoute
    }
    '/c/$token/mensalidades': {
      id: '/c/$token/mensalidades'
      path: '/mensalidades'
      fullPath: '/c/$token/mensalidades'
      preLoaderRoute: typeof CTokenMensalidadesRouteImport
      parentRoute: typeof CTokenRoute
    }
    '/c/$token/presencas': {
      id: '/c/$token/presencas'
      path: '/presencas'
      fullPath: '/c/$token/presencas'
      preLoaderRoute: typeof CTokenPresencasRouteImport
      parentRoute: typeof CTokenRoute
    }
    '/_authenticated/_shell/eventos/': {
      id: '/_authenticated/_shell/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof AuthenticatedShellEventosIndexRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/eventos/$id': {
      id: '/_authenticated/_shell/eventos/$id'
      path: '/eventos/$id'
      fullPath: '/eventos/$id'
      preLoaderRoute: typeof AuthenticatedShellEventosIdRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/eventos/checkins': {
      id: '/_authenticated/_shell/eventos/checkins'
      path: '/eventos/checkins'
      fullPath: '/eventos/checkins'
      preLoaderRoute: typeof AuthenticatedShellEventosCheckinsRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/eventos/novo': {
      id: '/_authenticated/_shell/eventos/novo'
      path: '/eventos/novo'
      fullPath: '/eventos/novo'
      preLoaderRoute: typeof AuthenticatedShellEventosNovoRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/hospitalaria/cardapios': {
      id: '/_authenticated/_shell/hospitalaria/cardapios'
      path: '/hospitalaria/cardapios'
      fullPath: '/hospitalaria/cardapios'
      preLoaderRoute: typeof AuthenticatedShellHospitalariaCardapiosRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/hospitalaria/escala': {
      id: '/_authenticated/_shell/hospitalaria/escala'
      path: '/hospitalaria/escala'
      fullPath: '/hospitalaria/escala'
      preLoaderRoute: typeof AuthenticatedShellHospitalariaEscalaRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/membros/': {
      id: '/_authenticated/_shell/membros/'
      path: '/membros'
      fullPath: '/membros/'
      preLoaderRoute: typeof AuthenticatedShellMembrosIndexRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/membros/$id': {
      id: '/_authenticated/_shell/membros/$id'
      path: '/membros/$id'
      fullPath: '/membros/$id'
      preLoaderRoute: typeof AuthenticatedShellMembrosIdRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/membros/novo': {
      id: '/_authenticated/_shell/membros/novo'
      path: '/membros/novo'
      fullPath: '/membros/novo'
      preLoaderRoute: typeof AuthenticatedShellMembrosNovoRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/ongoing/$id': {
      id: '/_authenticated/_shell/ongoing/$id'
      path: '/ongoing/$id'
      fullPath: '/ongoing/$id'
      preLoaderRoute: typeof AuthenticatedShellOngoingIdRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/regional/': {
      id: '/_authenticated/_shell/regional/'
      path: '/regional'
      fullPath: '/regional/'
      preLoaderRoute: typeof AuthenticatedShellRegionalIndexRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/regional/calendario': {
      id: '/_authenticated/_shell/regional/calendario'
      path: '/regional/calendario'
      fullPath: '/regional/calendario'
      preLoaderRoute: typeof AuthenticatedShellRegionalCalendarioRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/regional/capitulos': {
      id: '/_authenticated/_shell/regional/capitulos'
      path: '/regional/capitulos'
      fullPath: '/regional/capitulos'
      preLoaderRoute: typeof AuthenticatedShellRegionalCapitulosRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/regional/membros': {
      id: '/_authenticated/_shell/regional/membros'
      path: '/regional/membros'
      fullPath: '/regional/membros'
      preLoaderRoute: typeof AuthenticatedShellRegionalMembrosRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/regional/regioes': {
      id: '/_authenticated/_shell/regional/regioes'
      path: '/regional/regioes'
      fullPath: '/regional/regioes'
      preLoaderRoute: typeof AuthenticatedShellRegionalRegioesRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/sindicancias/fichas': {
      id: '/_authenticated/_shell/sindicancias/fichas'
      path: '/sindicancias/fichas'
      fullPath: '/sindicancias/fichas'
      preLoaderRoute: typeof AuthenticatedShellSindicanciasFichasRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/sindicancias/processos': {
      id: '/_authenticated/_shell/sindicancias/processos'
      path: '/sindicancias/processos'
      fullPath: '/sindicancias/processos'
      preLoaderRoute: typeof AuthenticatedShellSindicanciasProcessosRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/tesouraria/cobrancas': {
      id: '/_authenticated/_shell/tesouraria/cobrancas'
      path: '/tesouraria/cobrancas'
      fullPath: '/tesouraria/cobrancas'
      preLoaderRoute: typeof AuthenticatedShellTesourariaCobrancasRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/tesouraria/fluxo': {
      id: '/_authenticated/_shell/tesouraria/fluxo'
      path: '/tesouraria/fluxo'
      fullPath: '/tesouraria/fluxo'
      preLoaderRoute: typeof AuthenticatedShellTesourariaFluxoRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/tesouraria/mensalidades': {
      id: '/_authenticated/_shell/tesouraria/mensalidades'
      path: '/tesouraria/mensalidades'
      fullPath: '/tesouraria/mensalidades'
      preLoaderRoute: typeof AuthenticatedShellTesourariaMensalidadesRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
    '/_authenticated/_shell/membros/$id_/editar': {
      id: '/_authenticated/_shell/membros/$id_/editar'
      path: '/membros/$id/editar'
      fullPath: '/membros/$id/editar'
      preLoaderRoute: typeof AuthenticatedShellMembrosIdEditarRouteImport
      parentRoute: typeof AuthenticatedShellRouteRoute
    }
  }
}

interface AuthenticatedShellRouteRouteChildren {
  AuthenticatedShellAtasRoute: typeof AuthenticatedShellAtasRoute
  AuthenticatedShellCalendarioRoute: typeof AuthenticatedShellCalendarioRoute
  AuthenticatedShellConfiguracoesRoute: typeof AuthenticatedShellConfiguracoesRoute
  AuthenticatedShellFinanceiroRoute: typeof AuthenticatedShellFinanceiroRoute
  AuthenticatedShellGestaoRoute: typeof AuthenticatedShellGestaoRoute
  AuthenticatedShellInicioRoute: typeof AuthenticatedShellInicioRoute
  AuthenticatedShellMaisRoute: typeof AuthenticatedShellMaisRoute
  AuthenticatedShellPerfilRoute: typeof AuthenticatedShellPerfilRoute
  AuthenticatedShellPresencasRoute: typeof AuthenticatedShellPresencasRoute
  AuthenticatedShellEventosIdRoute: typeof AuthenticatedShellEventosIdRoute
  AuthenticatedShellEventosCheckinsRoute: typeof AuthenticatedShellEventosCheckinsRoute
  AuthenticatedShellEventosNovoRoute: typeof AuthenticatedShellEventosNovoRoute
  AuthenticatedShellHospitalariaCardapiosRoute: typeof AuthenticatedShellHospitalariaCardapiosRoute
  AuthenticatedShellHospitalariaEscalaRoute: typeof AuthenticatedShellHospitalariaEscalaRoute
  AuthenticatedShellMembrosIdRoute: typeof AuthenticatedShellMembrosIdRoute
  AuthenticatedShellMembrosNovoRoute: typeof AuthenticatedShellMembrosNovoRoute
  AuthenticatedShellOngoingIdRoute: typeof AuthenticatedShellOngoingIdRoute
  AuthenticatedShellRegionalCalendarioRoute: typeof AuthenticatedShellRegionalCalendarioRoute
  AuthenticatedShellRegionalCapitulosRoute: typeof AuthenticatedShellRegionalCapitulosRoute
  AuthenticatedShellRegionalMembrosRoute: typeof AuthenticatedShellRegionalMembrosRoute
  AuthenticatedShellRegionalRegioesRoute: typeof AuthenticatedShellRegionalRegioesRoute
  AuthenticatedShellSindicanciasFichasRoute: typeof AuthenticatedShellSindicanciasFichasRoute
  AuthenticatedShellSindicanciasProcessosRoute: typeof AuthenticatedShellSindicanciasProcessosRoute
  AuthenticatedShellTesourariaCobrancasRoute: typeof AuthenticatedShellTesourariaCobrancasRoute
  AuthenticatedShellTesourariaFluxoRoute: typeof AuthenticatedShellTesourariaFluxoRoute
  AuthenticatedShellTesourariaMensalidadesRoute: typeof AuthenticatedShellTesourariaMensalidadesRoute
  AuthenticatedShellEventosIndexRoute: typeof AuthenticatedShellEventosIndexRoute
  AuthenticatedShellMembrosIndexRoute: typeof AuthenticatedShellMembrosIndexRoute
  AuthenticatedShellRegionalIndexRoute: typeof AuthenticatedShellRegionalIndexRoute
  AuthenticatedShellMembrosIdEditarRoute: typeof AuthenticatedShellMembrosIdEditarRoute
}

const AuthenticatedShellRouteRouteChildren: AuthenticatedShellRouteRouteChildren =
  {
    AuthenticatedShellAtasRoute: AuthenticatedShellAtasRoute,
    AuthenticatedShellCalendarioRoute: AuthenticatedShellCalendarioRoute,
    AuthenticatedShellConfiguracoesRoute: AuthenticatedShellConfiguracoesRoute,
    AuthenticatedShellFinanceiroRoute: AuthenticatedShellFinanceiroRoute,
    AuthenticatedShellGestaoRoute: AuthenticatedShellGestaoRoute,
    AuthenticatedShellInicioRoute: AuthenticatedShellInicioRoute,
    AuthenticatedShellMaisRoute: AuthenticatedShellMaisRoute,
    AuthenticatedShellPerfilRoute: AuthenticatedShellPerfilRoute,
    AuthenticatedShellPresencasRoute: AuthenticatedShellPresencasRoute,
    AuthenticatedShellEventosIdRoute: AuthenticatedShellEventosIdRoute,
    AuthenticatedShellEventosCheckinsRoute:
      AuthenticatedShellEventosCheckinsRoute,
    AuthenticatedShellEventosNovoRoute: AuthenticatedShellEventosNovoRoute,
    AuthenticatedShellHospitalariaCardapiosRoute:
      AuthenticatedShellHospitalariaCardapiosRoute,
    AuthenticatedShellHospitalariaEscalaRoute:
      AuthenticatedShellHospitalariaEscalaRoute,
    AuthenticatedShellMembrosIdRoute: AuthenticatedShellMembrosIdRoute,
    AuthenticatedShellMembrosNovoRoute: AuthenticatedShellMembrosNovoRoute,
    AuthenticatedShellOngoingIdRoute: AuthenticatedShellOngoingIdRoute,
    AuthenticatedShellRegionalCalendarioRoute:
      AuthenticatedShellRegionalCalendarioRoute,
    AuthenticatedShellRegionalCapitulosRoute:
      AuthenticatedShellRegionalCapitulosRoute,
    AuthenticatedShellRegionalMembrosRoute:
      AuthenticatedShellRegionalMembrosRoute,
    AuthenticatedShellRegionalRegioesRoute:
      AuthenticatedShellRegionalRegioesRoute,
    AuthenticatedShellSindicanciasFichasRoute:
      AuthenticatedShellSindicanciasFichasRoute,
    AuthenticatedShellSindicanciasProcessosRoute:
      AuthenticatedShellSindicanciasProcessosRoute,
    AuthenticatedShellTesourariaCobrancasRoute:
      AuthenticatedShellTesourariaCobrancasRoute,
    AuthenticatedShellTesourariaFluxoRoute:
      AuthenticatedShellTesourariaFluxoRoute,
    AuthenticatedShellTesourariaMensalidadesRoute:
      AuthenticatedShellTesourariaMensalidadesRoute,
    AuthenticatedShellEventosIndexRoute: AuthenticatedShellEventosIndexRoute,
    AuthenticatedShellMembrosIndexRoute: AuthenticatedShellMembrosIndexRoute,
    AuthenticatedShellRegionalIndexRoute: AuthenticatedShellRegionalIndexRoute,
    AuthenticatedShellMembrosIdEditarRoute:
      AuthenticatedShellMembrosIdEditarRoute,
  }

const AuthenticatedShellRouteRouteWithChildren =
  AuthenticatedShellRouteRoute._addFileChildren(
    AuthenticatedShellRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedShellRouteRoute: typeof AuthenticatedShellRouteRouteWithChildren
  AuthenticatedSelecionarCapituloRoute: typeof AuthenticatedSelecionarCapituloRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedShellRouteRoute: AuthenticatedShellRouteRouteWithChildren,
  AuthenticatedSelecionarCapituloRoute: AuthenticatedSelecionarCapituloRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DocumentacaoRouteRouteChildren {
  DocumentacaoGuiaRoute: typeof DocumentacaoGuiaRoute
  DocumentacaoOpenSourceRoute: typeof DocumentacaoOpenSourceRoute
  DocumentacaoTecnicaRoute: typeof DocumentacaoTecnicaRoute
  DocumentacaoIndexRoute: typeof DocumentacaoIndexRoute
}

const DocumentacaoRouteRouteChildren: DocumentacaoRouteRouteChildren = {
  DocumentacaoGuiaRoute: DocumentacaoGuiaRoute,
  DocumentacaoOpenSourceRoute: DocumentacaoOpenSourceRoute,
  DocumentacaoTecnicaRoute: DocumentacaoTecnicaRoute,
  DocumentacaoIndexRoute: DocumentacaoIndexRoute,
}

const DocumentacaoRouteRouteWithChildren =
  DocumentacaoRouteRoute._addFileChildren(DocumentacaoRouteRouteChildren)

interface CTokenRouteChildren {
  CTokenEuRoute: typeof CTokenEuRoute
  CTokenFluxoRoute: typeof CTokenFluxoRoute
  CTokenMensalidadesRoute: typeof CTokenMensalidadesRoute
  CTokenPresencasRoute: typeof CTokenPresencasRoute
  CTokenIndexRoute: typeof CTokenIndexRoute
}

const CTokenRouteChildren: CTokenRouteChildren = {
  CTokenEuRoute: CTokenEuRoute,
  CTokenFluxoRoute: CTokenFluxoRoute,
  CTokenMensalidadesRoute: CTokenMensalidadesRoute,
  CTokenPresencasRoute: CTokenPresencasRoute,
  CTokenIndexRoute: CTokenIndexRoute,
}

const CTokenRouteWithChildren =
  CTokenRoute._addFileChildren(CTokenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  DocumentacaoRouteRoute: DocumentacaoRouteRouteWithChildren,
  AtualizarCadastroRoute: AtualizarCadastroRoute,
  AuthRoute: AuthRoute,
  AtaTokenRoute: AtaTokenRoute,
  CTokenRoute: CTokenRouteWithChildren,
  FluxoCaixaTokenRoute: FluxoCaixaTokenRoute,
  MensalidadesTokenRoute: MensalidadesTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
